### ISSUE TITLE
Player, Target and Focus UnitFrames

### ISSUE THREAD

**Issue by Reshuffling** [kurapica/AshToAsh#1]
Any plans on making templates for the Player, Target and Focus UnitFrames too?

**Comment by kurapica** [comment]
There is an unit watch panel, you can add target, focus on it.

Also in my repo, there is a AshUnitFrame for those unit frames, it use the same framework like the AshToAsh, but I only use it to hide the system's unit frames, so I don't release it in the curseforge.

I use my Aim for the nameplates, that's enough for me.
