### ISSUE TITLE
Bottom to Top orientation switch doesn't work

### ISSUE THREAD

**Issue by Bonkeybee** [kurapica/AshToAsh#2]
For a single column "show only dead" unit frame, the bottom to top orientation doesn't work after frames are locked.
![image](https://user-images.githubusercontent.com/9619823/143148915-ba16c7ac-8eaa-423d-b1f1-dedf9ef95b78.png)
![image](https://user-images.githubusercontent.com/9619823/143148963-e2f6fdbd-d48c-42c3-9647-f0462bf94576.png)

**Comment by kurapica** [comment]
That's not not working, it only means the orientation to place the unit, the panel is auto sized  for how many units is shown, so if you have only one unit to be shown, the panel will only show one unit frame at the first place.

I still have some panel settings not on the menu, I'm planning to create a new ui config auto-gen system, so a config panel will be used to replaced the dropdown menu, those settings will be given in the new config panel.
